name: Generate Japan Stock ICS
on:
  schedule:
    - cron: '0 17 * * *'  # JST 02:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: pip install ics requests

    - name: Generate ICS
      run: python generate.py

    - name: Deploy
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
